#!/bin/bash
#
# skript algab
echo -e "Sisesta kasutaja vanus: \c "
read vanus
#
if test $vanus -gt 0 -a $vanus -lt 11
then echo "Oled laps"
elif test $vanus -ge 11 -a $vanus -lt 18
then echo "oled nooruk"
elif test $vanus -ge 18 -a $vanus -lt 16
then echo "Oled täiskasvanu"
elif test $vanus -ge 63
then echo "Oled vana"
else echo "Viga sisestamisel"
fi
#
# skript lõppeb
