#!/bin/bash
#
# reisi korraldus
#
#
echo -n "Sisesta reisijate arv : "
read reis
echo -n "Sisesta bussi kohtade arv: "
read koht
#Siin on käsurida, et mida bussi täidetakse
busside_arv=`expr $reis / $koht`
#Järgmine rida näitab mitu istekohta tuleb puudu
puudu=`expr $reis % $koht`
if [ $puudu -eq 0 ]
      then echo "Kokku läheb $bussid bussi"
      else echo "Kokku on vaja `expr $bussid +1` bussi"
fi
#
#
#skripti lõpp
