#!/bin/bash
#
osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat"

echo -n "Select your os choice [Unix or Linux]"
read osch
#
if [ $osch -eq 1 ] ; then
echo "You pick up Unix"
else #### nested if i.e if within if ####
          if [ $osch -eq 2 ] ; then
             echo "You pick up Linux"
         else
             echo "What you dont like Unix/Linux OS..."
         fi
fi
#
#
