#!/bin/bash
#
# suvaline täisarv
#
echo -n "Täisarv: "
read arv 
summa=0
while [ $arv -ne 0 ]
do
jaak=$(($arv % 10))
summa=$(($summa + $jaak))
arv=$(($arv / 10))
done
echo "Numbrite summa on: $summa"
#
# skript lõpp
