#!/bin/bash
#
# algarv 
#
echo -e "sisesta siia arv: \c"
read arv
#
if [$arv -eq 0 -o $arv -eq 1 ]; then
echo "$arv on algarv"
fi
while [ $summa -lt $arv ]
#
if [ `expr $arv % $summa` -eq 0 ]
then
echo "$arv ei ole algarv"
fi
summa=$(($summa +1))
echo "$arv on algarv"
exit
#

