#!/bin/bash
#
# hüpotenuusi arvutus
#
echo -n "Sisesta a külg: "
read a
echo -n "Sisesta b külg: "
read b
#
# a ruut
a2=`echo "scale=2;$a^2" | bc`
# b ruut
b2=`echo "scale=2;$b^2" | bc`
# c ruut
c2=`echo "scale2;$a2+$b2" | bc`
# c on
c=`echo "scale=2;sqrt($c2)" | bc`
# väljastame c
echo "c = $c"
